# This is a basic workflow to help you get started with Actions

name: CI
run-name: ${{ github.actor }} init a workflow

env:
  GITHUB_ACTIONS: True

# Controls when the workflow will run
on:
  #push: branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  github-task-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - run: echo "${{ env.GITHUB_ACTIONS }}"
    - run: echo "Name of branch - ${{ github.head_ref }} and name of repo - ${{ github.repository }}"
    - run: echo "Action that start the workflow - ${{ github.event_name }}"
